@LogiTrack_HostAddress = http://localhost:5151
@LogiTrack_SecureHostAddress = https://localhost:7129

GET {{LogiTrack_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{LogiTrack_SecureHostAddress }}/api/inventory
Accept: application/json

###

GET {{LogiTrack_SecureHostAddress }}/api/inventory/4
Accept: application/json

###

GET {{LogiTrack_SecureHostAddress }}/api/orders
Accept: application/json

###
GET {{LogiTrack_SecureHostAddress }}/api/orders/1
Accept: application/json

###
POST {{LogiTrack_SecureHostAddress }}/api/Inventory/
Content-Type: application/json

{
  "itemId": "11",
  "name": "New Item",
  "quantity": "13",
  "location": "Warehouse A"
}

###
DELETE {{LogiTrack_SecureHostAddress }}/api/Inventory/11
Content-Type: application/json

{
  "itemId": "11"
}

###
POST {{LogiTrack_SecureHostAddress }}/api/orders
Content-Type: application/json

{
  "customerName": "Darth Vader",
  "orderDate": "2025-08-05T10:00:00",
  "items": [
    {
      "inventoryItemId": 1,
      "quantityOrdered": 2
    },
    {
      "inventoryItemId": 3,
      "quantityOrdered": 1
    }
  ]
}

###
POST {{LogiTrack_SecureHostAddress }}/api/orders
Content-Type: application/json

{
  "customerName": "Darth Vader",
  "orderDate": "2025-08-05T15:00:46.741Z",
  "items": [
    {
      "inventoryItemId": 1,
      "quantityOrdered": 2
    },
    {
      "inventoryItemId": 3,
      "quantityOrdered": 1
    }
  ]
}

###
PUT {{LogiTrack_SecureHostAddress }}/api/orders/1
Content-Type: application/json

{
  "customerName": "Emperor Palpatine Updated",
  "orderDate": "2025-08-05T15:15:58.806Z",
  "items": [
    {
      "inventoryItemId": 1,
      "quantityOrdered": 5
    },
    {
      "inventoryItemId": 2,
      "quantityOrdered": 3
    }
  ]
}


